### ISSUE TITLE
Cannot change white background behind image

### ISSUE THREAD

**Issue by faridanthony** [Mawi137/ngx-image-cropper#311]
There appears to be a white background behind the image-cropper that I cannot change.

**Comment by Mawi137** [comment]
That should be possible with some css.

**Comment by faridanthony** [comment]
Seems like it can be partially by the .overlay {
    outline:
}

But it looks like there’s some opacity difference as the color is lighter than whatever i specify

**Comment by Mawi137** [comment]
That's the outline of the `.cropper` you still see. Easiest solution is to set that to your background color as well but with a transparency.

**Comment by CalebeRios** [comment]
@faridanthony did you change background color? Can you share your code?

**Comment by maddy2894** [comment]
Even I have the same problem, any solution?

**Comment by Mawi137** [comment]
I just released version 3.1.7. In the readme you'll find 2 css variables you can use to change the background. They should be the same color, but one should have a transparancy.

**Comment by faridanthony** [comment]
Awesome. I’ll check it out tomorrow. Thanks @Mawi137 !

**Comment by CalebeRios** [comment]
@Mawi137worked here, thanks!

**Comment by Mawi137** [comment]
Great! Closing the issue.

**Comment by faridanthony** [comment]
It didn't completely resolve my issue but helped. After looking into it a bit more, looks like the issue is with FlexLayout.

**Comment by emelieedman** [comment]
I'm able to change the background-color with `--cropper-overlay-color` but making it transparent doesn't work. Any solutions? I get a line underneath the image and would like to remove the background completely..

**Comment by jstjnsn** [comment]
For me the solution was to set `--cropper-overlay-color` to `rgba(0, 0, 0, 0)`, basically a background with full transparency. I needed this because I use this component in an app with a background image, which the white background was in front of. @emelieedman in case you still need this :)
